# docker-compose.yml

version: "3.7"
services:
  auth_service:
    container_name: auth_service
    build:
      context: ./auth-service
    network_mode: "host"
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "1m"
  
  reminder_service:
    container_name: reminder_service
    build:
      context: ./reminder-service
    network_mode: "host"
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "1m"
  
  schedule_service:
    container_name: schedule_service
    build:
      context: ./schedule-service
    network_mode: "host"
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "1m"

