# docker-compose.yml

version: "3.7"
services:
  auth_service:
    container_name: auth_service
    build:
      context: ./auth-service
    depends_on:
      mongodb:
        condition: service_healthy
      rabbit_mq:
        condition: service_started
    network_mode: "host"
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "1m"
  
  reminder_service:
    container_name: reminder_service
    build:
      context: ./reminder-service
    depends_on:
      mongodb:
        condition: service_healthy
      rabbit_mq:
        condition: service_started
    network_mode: "host"
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "1m"
  
  schedule_service:
    container_name: schedule_service
    build:
      context: ./schedule-service
    depends_on:
      mongodb:
        condition: service_healthy
      rabbit_mq:
        condition: service_started
    network_mode: "host"
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "1m"

  gateway_service:
    container_name: gateway_service
    build:
      context: ./gateway-service
    network_mode: "host"
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "1m"

  rabbit_mq:
    image: rabbitmq:3.9-management
  mongodb:
    image: mongo:4.4.10