FROM node:alpine
RUN mkdir -p /opt/app
WORKDIR /opt/app
RUN adduser --system app
RUN apk add --no-cache git
COPY src/ .
RUN npm install
USER app
EXPOSE 5001
EXPOSE 6001
CMD [ "npm", "run", "start:production" ]
